### ISSUE TITLE
horizontal zoom not working as individual (same issue)

### ISSUE THREAD

**Issue by keskink** [SunPointed/MPFlutterChart#118]
horizontal zoom not working as individual even when pinchZoomEnabled: false
it is zooming proportional when I try to zoom horizontal.
But vertical zooming working individual.

**Comment by SunPointed** [comment]
what chart you used? I remember this is solved

**Comment by keskink** [comment]
I wrote before. This issue same with closed by you. 
I can not get correct solution by you. That is why I open this issue again.
You can fallow all history on closed issue. But actually it is not really solved my issue.

Regards

Ismail

**Comment by keskink** [comment]
I am still waiting solution.
Thank you
